server:
  http2:
    enabled: true

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: TaskManagementHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jta:
    enabled: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: OFF
    com.omori.taskmanagement: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: ${JWT_SECRET_KEY}
  #issuer: www.farukgenc.com
  expirationMinute: 10

swagger:
  contact-name: Omori
  contact-mail: omori@lazydev.com
  contact-url: https://github/XIVIXMMI.com
  app-name: Spring Boot Boilerplate Project
  app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot(3.5.0), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API)"
  app-version: 3.5.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
